name: signupinscreen
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.6

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/c1.jpg
    - images/m1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/m2.jpg
    - images/cats/tshirt.png
    - images/cats/dress.png
    - images/cats/formal.png
    - images/cats/informal.png
    - images/cats/shoe.png
    - images/cats/jeans.png
    - images/cats/accessories.png
    - images/products/blazer1.jpeg
    - images/products/dress1.jpeg
    - images/lg.png
    - images/google.png